name: Java CI Pipeline

on:
  pull_request:
    branches:
      - assignment-1  # Runs only on PRs to the assignment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Compile Java Program
        run: javac -d bin src/Main.java

      - name: Run Java Application
        run: java -cp bin Main

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install JUnit
        run: |
          mkdir -p lib
          curl -L -o lib/junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar

      - name: Run Tests
        run: java -jar lib/junit-platform-console-standalone.jar --class-path bin --scan-class-path

  containerize:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-java-app .

      - name: Run Container
        run: docker run --rm my-java-app
